### ISSUE TITLE
browseRelease() problem

### ISSUE THREAD

**Issue by alexanderahlsen** [mikealmond/MusicBrainz#12]
Hello,

I've been adding some parts to the library to fit my needs, but now I've run into a problem I can't seem to solve.
When I use browseRelease I already have the mbid and want to get the recordnings off of that track.
I've had a look at your code and I modified it to look like this:

$details = $brainz->browseRelease('aad08360-f5cd-4e3b-9df6-88dae1b3e3f2', $includes, 2);

I removed the 'artist' from your example since you just need the mbid to get the release. The url in browser look like this:
http://musicbrainz.org/ws/2/release/61bf0388-b8a9-48f4-81d1-7eb02706dfb0?inc=recordings

Bu that doesn't work, it doesn't allow me to drop out the 'artist', but I don't really need that first entity because we can just go straight to it.

I've tried to modify MusicBrainz.php (around line 458) to remove the $entity but that doesn't work. And if I add a new empty entity it adds a "?=" before the mbid so the release isn't found.

Can you please help me with this?
Should I add a new function maybe and duplicate the browse function and reomve the entity?

**Comment by mikealmond** [comment]
What you want to perform is a lookup.

```php
$details = $brainz->lookup('release', '61bf0388-b8a9-48f4-81d1-7eb02706dfb0', array('recordings'));
```

Another way to do this is to browse the recordings based on the release. 
```php
$details = $brainz->browseRecording('release', 'aad08360-f5cd-4e3b-9df6-88dae1b3e3f2', $includes, 2);
```

Sorry for the long delay.
