### ISSUE TITLE
Bad RequestsHttpAdapter file name

### ISSUE THREAD

**Issue by Afterster** [mikealmond/MusicBrainz#16]
*RequestsHttpAdapter* class file name is named *RequestsAdapter.php* which makes autload to fail. The file name should be *RequestsHttpAdapter.php*

Thank you.

**Comment by mikealmond** [comment]
Thanks! This has been fixed, pushed to master, and tagged with v0.2.2

**Comment by Afterster** [comment]
Thanks ;)
